### ISSUE TITLE
Locale test fails with newer DateTime::Locale ($DateTime::Locale::VERSION >= 1.00)

### ISSUE THREAD

**Issue by rivy** [jhoblitt/DateTime-HiRes#1]
DateTime::Locale changed the canonical form from using internal underscores to using internal dashes. This makes testing fail, blocking unforced installs.

Test output:

```
t\01_load.t .. ok
t\02_now.t ... 1/6
#   Failed test 'accepted locale parameter'
#   at t\02_now.t line 35.
#          got: 'ar-EG'
#     expected: 'ar_EG'
# Looks like you failed 1 test of 6.
t\02_now.t ... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests

Test Summary Report
-------------------
t\02_now.t (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
Files=2, Tests=7,  1 wallclock secs ( 0.05 usr +  0.06 sys =  0.11 CPU)
Result: FAIL
Failed 1/2 test programs. 1/7 subtests failed.
dmake:  Error code 129, while making 'test'
```

Also reported on CPAN RT @ https://rt.cpan.org/Public/Bug/Display.html?id=109088 .

**Comment by rivy** [comment]
@jhoblitt , I haven't seen an updated version on CPAN as of yet.

Are you waiting for other changes before updating it on CPAN?

**Comment by christopherraa** [comment]
@jhoblitt I mistakenly commented on the pullrequest associated with this issue, but mean to comment here. Basically I echo what @rivy said. Any chance of getting an updated version to CPAN?

**Comment by JustThisGuyAZ** [comment]
@jhoblitt Not to pile on, but I'd like to 3rd this request to get this fix to CPAN. It's making it difficult to automate our install. Thanks!

**Comment by rivy** [comment]
Given the brevity of the module, (eg ...
```
use DateTime;
use Time::HiRes;
sub now { shift; DateTime->from_epoch( epoch => Time::HiRes::time, @_ ) }
```
and the unfortunate lack of response, I've just reimplemented the function and removed the dependency from all of my code.
